/*
 * adat_rx_bitdiff.c; cycle-accurate timing verification of the adat_rx PIO
 * NRZI decoder against divider quantization and source clock offset.
 *
 * Executes the PIO program instruction by instruction, including fractional
 * clock-divider behavior (first-order accumulator, matching RP2350 clkdiv),
 * against a wire stream generated by the firmware's own ADAT encoder at a
 * configurable rate offset. Frames are self-identifying (channel 0 carries
 * a counter), so the frame-level oracle judges decode fidelity exactly the
 * way the firmware does (header verify + content), immune to alignment
 * ambiguity in repetitive audio patterns.
 *
 * Three program models are kept: the ORIGINAL shipped decoder (model 0,
 * 8 PIO cycles per cell on a fractional divider) whose one-way poll ratchet
 * deleted bits at 44.1 kHz, an early-poll variant (model 1) that proved
 * insufficient, and the CURRENT divider-1.0 counter-loop program (model 2,
 * matches adat_input.pio). The no-arg run is a regression matrix: model 0's
 * known failures must reproduce (simulator fidelity) and model 2 must be
 * bit-exact at both rates across +-1000 ppm. The acquisition regression also
 * verifies the current exact-timing probe policy: the wrong family is dirty,
 * then the matching 48/44.1 kHz candidate decodes cleanly.
 *
 * cc -O2 -o adat_rx_bitdiff adat_rx_bitdiff.c && ./adat_rx_bitdiff
 * Single case: ./adat_rx_bitdiff <fs> <src_ppm> <div_or_y> <model>
 * (diff_streams() below is an unused-by-default manual diagnostic that
 * classifies raw bitstream divergences; wire it into main when needed.)
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#define SYS_CLK_HZ 307200000ull
#define ADAT_SYNC_HEADER 0x8010u
#define N_FRAMES 2000

static uint16_t adat_token_lut[256];
static uint16_t adat_hdr_nrzi[2];
static uint32_t adat_hdr_exit[2];

static void tx_init(void) {
    for (uint32_t b = 0; b < 256; b++) {
        uint32_t stuffed = 0x210u | ((b & 0xF0u) << 1) | (b & 0x0Fu);
        uint32_t t = 0, l = 0;
        for (int k = 9; k >= 0; k--) { l ^= (stuffed >> k) & 1u; t = (t << 1) | l; }
        adat_token_lut[b] = (uint16_t)t;
    }
    for (uint32_t lvl = 0; lvl < 2; lvl++) {
        uint32_t t = 0, l = lvl;
        for (int k = 15; k >= 0; k--) { l ^= (ADAT_SYNC_HEADER >> k) & 1u; t = (t << 1) | l; }
        adat_hdr_nrzi[lvl] = (uint16_t)t;
        adat_hdr_exit[lvl] = l;
    }
}

static uint32_t adat_encode_frame(uint32_t *w, const int32_t s24[8], uint32_t entry) {
    uint32_t hdr = adat_hdr_nrzi[entry];
    uint32_t m = (0u - adat_hdr_exit[entry]) & 0x3FFu;
    uint32_t c[8];
    for (int ch = 0; ch < 8; ch++) {
        uint32_t s = (uint32_t)s24[ch];
        uint32_t t2 = adat_token_lut[(s >> 16) & 0xFFu] ^ m; m = (0u - (t2 & 1u)) & 0x3FFu;
        uint32_t t1 = adat_token_lut[(s >> 8) & 0xFFu] ^ m;  m = (0u - (t1 & 1u)) & 0x3FFu;
        uint32_t t0 = adat_token_lut[s & 0xFFu] ^ m;         m = (0u - (t0 & 1u)) & 0x3FFu;
        c[ch] = (t2 << 20) | (t1 << 10) | t0;
    }
    w[0] = (hdr << 16)  | (c[0] >> 14);
    w[1] = (c[0] << 18) | (c[1] >> 12);
    w[2] = (c[1] << 20) | (c[2] >> 10);
    w[3] = (c[2] << 22) | (c[3] >> 8);
    w[4] = (c[3] << 24) | (c[4] >> 6);
    w[5] = (c[4] << 26) | (c[5] >> 4);
    w[6] = (c[5] << 28) | (c[6] >> 2);
    w[7] = (c[6] << 30) |  c[7];
    return m & 1u;
}

// levels[] = wire line levels; ideal[] = logical NRZI decode (level xor prev)
static uint8_t levels[(uint64_t)N_FRAMES * 256 + 8];
static uint8_t ideal[(uint64_t)N_FRAMES * 256 + 8];
static uint8_t emitted[(uint64_t)N_FRAMES * 256 + 4096];
static uint64_t n_levels, n_emitted;

// Every frame is self-identifying: channel 0 carries the frame counter.
// Channels 1..7 are random, except every 16th frame is silence (long zero
// runs) and every 16th+8 is 0x555555/full-scale (dense transitions).
static int32_t ref_frames[N_FRAMES][8];

static void gen_stream(unsigned seed) {
    srand(seed);
    n_levels = 0;
    uint32_t entry = 0;
    for (int f = 0; f < N_FRAMES; f++) {
        int32_t *s = ref_frames[f];
        s[0] = f & 0xFFFFFF;
        for (int ch = 1; ch < 8; ch++) {
            if ((f & 15) == 0) s[ch] = 0;
            else if ((f & 15) == 8) s[ch] = (ch & 1) ? 0x555555 : ((ch & 2) ? 0x7FFFFF : 0x800000 >> 0);
            else s[ch] = (int32_t)((((uint32_t)rand() << 16) ^ (uint32_t)rand()) & 0xFFFFFFu);
        }
        uint32_t w[8];
        entry = adat_encode_frame(w, s, entry);
        for (int i = 0; i < 8; i++)
            for (int b = 31; b >= 0; b--)
                levels[n_levels++] = (w[i] >> b) & 1u;
    }
    uint8_t prev = 0;
    for (uint64_t i = 0; i < n_levels; i++) {
        ideal[i] = levels[i] ^ prev;
        prev = levels[i];
    }
}

// Cycle-accurate PIO run. Three program models:
//   model 0: the original 13-instruction adat_rx (8 PIO cycles per cell on a
//            fractional divider; single post-edge poll at +8; fast-side ratchet)
//   model 1: model 0 plus an early poll at +6 (insufficient: the fractional
//            divider's cell-length modulation still defeats it)
//   model 2: counter-loop redesign at divider 1.0: integer cell length in
//            sys cycles (2*y+5), 2-cycle poll granularity, edge re-anchoring
//            within 2 cycles both directions. div_16_8 is reinterpreted as
//            the y reload value for this model.
static int pio_model = 0;

static void run_pio(double tx_bit_sys, uint32_t div_16_8) {
    uint32_t int_part = div_16_8 >> 8, frac = div_16_8 & 0xFFu, acc = 0;
    double t = 0.0;
    n_emitted = 0;
    #define STEP() do { acc += frac; t += (double)(int_part + (acc >= 256u ? 1u : 0u)); if (acc >= 256u) acc -= 256u; } while (0)
    #define TAKE(n) do { for (int _i = 0; _i < (n); _i++) STEP(); } while (0)
    #define EMIT(b) do { if (n_emitted < sizeof(emitted)) emitted[n_emitted++] = (b); } while (0)
    if (pio_model == 0) {
        uint32_t pc = 1;
        for (;;) {
            uint64_t idx = (uint64_t)(t / tx_bit_sys);
            if (idx >= n_levels) break;
            int lvl = levels[idx];
            switch (pc) {
            case 0:  EMIT(1); TAKE(6); pc = 1; break;
            case 1:  TAKE(1); pc = lvl ? 5 : 2; break;
            case 2:  TAKE(3); pc = 3; break;
            case 3:  TAKE(1); pc = lvl ? 5 : 4; break;
            case 4:  EMIT(0); TAKE(3); pc = 1; break;
            case 5:  EMIT(1); TAKE(7); pc = 6; break;
            case 6:  TAKE(1); pc = lvl ? 8 : 7; break;
            case 7:  TAKE(1); pc = 0; break;
            case 8:  TAKE(3); pc = 9; break;
            case 9:  TAKE(1); pc = lvl ? 11 : 10; break;
            case 10: TAKE(1); pc = 0; break;
            case 11: EMIT(0); TAKE(2); pc = 12; break;
            case 12: TAKE(1); pc = 6; break;
            }
        }
    } else if (pio_model == 2) {
        // Counter-loop program at divider 1.0 (int_part=1, frac=0 forced by
        // caller passing y in div_16_8):
        //  0 l_top:  mov x,y
        //  1 l_poll: jmp pin l_edge
        //  2 l_dec:  jmp x-- l_poll
        //  3 l_zero: in null,1
        //  4 l_wrap: jmp l_top
        //  5 l_edge: in osr,1 [1]
        //  6 l_go:   jmp h_top
        //  7 h_top:  mov x,y
        //  8 h_poll: jmp pin h_cont
        //  9 h_fell: jmp h_edge
        // 10 h_cont: jmp x-- h_poll
        // 11 h_zero: in null,1
        // 12 h_wrap: jmp h_top
        // 13 h_edge: in osr,1
        // 14 h_go:   jmp l_top
        uint32_t yv = div_16_8;   // reinterpreted: y reload value
        int_part = 1; frac = 0; acc = 0;
        uint32_t x = 0, pc = 0;
        for (;;) {
            uint64_t idx = (uint64_t)(t / tx_bit_sys);
            if (idx >= n_levels) break;
            int lvl = levels[idx];
            switch (pc) {
            case 0:  x = yv; TAKE(1); pc = 1; break;
            case 1:  TAKE(1); pc = lvl ? 5 : 2; break;
            case 2:  TAKE(1); pc = x ? 1 : 3; if (x) x--; else x = 0xFFFFFFFFu, x = 0; break;
            case 3:  EMIT(0); TAKE(1); pc = 4; break;
            case 4:  TAKE(1); pc = 0; break;
            case 5:  EMIT(1); TAKE(8); pc = 6; break;   // in osr,1 [7]
            case 6:  TAKE(1); pc = 7; break;
            case 7:  x = yv; TAKE(1); pc = 8; break;
            case 8:  TAKE(1); pc = lvl ? 10 : 9; break;
            case 9:  TAKE(1); pc = 13; break;
            case 10: TAKE(1); pc = x ? 8 : 11; if (x) x--; break;
            case 11: EMIT(0); TAKE(1); pc = 12; break;
            case 12: TAKE(1); pc = 7; break;
            case 13: EMIT(1); TAKE(7); pc = 14; break;  // in osr,1 [6]
            case 14: TAKE(1); pc = 0; break;
            }
        }
    } else {
        // 0 l_one:in y,1[3]  1 l_pe:jmp pin h_one  2 l_pn:nop
        // 3 l_p0:jmp pin h_one  4 nop[2]  5 l_p1:jmp pin h_one
        // 6 in null,1[2] wrap->3
        // 7 h_one:in y,1[4]  8 h_pe:jmp pin h_pn  9 jmp l_one  10 h_pn:nop
        // 11 h_p0:jmp pin h_s0  12 jmp l_one  13 h_s0:nop[2]
        // 14 h_p1:jmp pin h_s1  15 jmp l_one  16 h_s1:in null,1[1]  17 jmp h_p0
        uint32_t pc = 3;
        for (;;) {
            uint64_t idx = (uint64_t)(t / tx_bit_sys);
            if (idx >= n_levels) break;
            int lvl = levels[idx];
            switch (pc) {
            case 0:  EMIT(1); TAKE(4); pc = 1; break;
            case 1:  TAKE(1); pc = lvl ? 7 : 2; break;
            case 2:  TAKE(1); pc = 3; break;
            case 3:  TAKE(1); pc = lvl ? 7 : 4; break;
            case 4:  TAKE(3); pc = 5; break;
            case 5:  TAKE(1); pc = lvl ? 7 : 6; break;
            case 6:  EMIT(0); TAKE(3); pc = 3; break;
            case 7:  EMIT(1); TAKE(5); pc = 8; break;
            case 8:  TAKE(1); pc = lvl ? 10 : 9; break;
            case 9:  TAKE(1); pc = 0; break;
            case 10: TAKE(1); pc = 11; break;
            case 11: TAKE(1); pc = lvl ? 13 : 12; break;
            case 12: TAKE(1); pc = 0; break;
            case 13: TAKE(3); pc = 14; break;
            case 14: TAKE(1); pc = lvl ? 16 : 15; break;
            case 15: TAKE(1); pc = 0; break;
            case 16: EMIT(0); TAKE(2); pc = 17; break;
            case 17: TAKE(1); pc = 11; break;
            }
        }
    }
    #undef STEP
    #undef TAKE
    #undef EMIT
}

static const uint32_t *rx_words;
static uint32_t rx_nwords;

static bool rx_decode_frame(uint32_t rd, uint32_t k, int32_t *smp) {
    uint32_t w[8];
    if (k == 0) {
        for (uint32_t i = 0; i < 8u; i++) w[i] = rx_words[rd + i];
    } else {
        uint32_t prev = rx_words[rd];
        for (uint32_t i = 0; i < 8u; i++) {
            uint32_t next = rx_words[rd + i + 1u];
            w[i] = (prev << k) | (next >> (32u - k));
            prev = next;
        }
    }
    if ((w[0] & 0xFFF00000u) != 0x80100000u) return false;
    for (uint32_t ch = 0; ch < 8u; ch++) {
        uint32_t p = 16u + 30u * ch;
        uint32_t a = w[p >> 5];
        uint32_t b = ((p >> 5) < 7u) ? w[(p >> 5) + 1u] : 0u;
        uint32_t sh = p & 31u;
        uint32_t v = (uint32_t)(((((uint64_t)a << 32) | b) >> (34u - sh))) & 0x3FFFFFFFu;
        uint32_t s24 = (((v >> 25) & 0xFu) << 20) | (((v >> 20) & 0xFu) << 16) |
                       (((v >> 15) & 0xFu) << 12) | (((v >> 10) & 0xFu) << 8)  |
                       (((v >> 5)  & 0xFu) << 4)  |   (v         & 0xFu);
        smp[ch] = (int32_t)(s24 << 8);
    }
    return true;
}

static bool rx_scan(uint32_t *out_word, uint32_t *out_bit, uint32_t from) {
    for (uint32_t i = from; i + 1 < rx_nwords; i++) {
        uint32_t prev = rx_words[i], curr = rx_words[i + 1];
        if (!(prev | curr)) continue;
        uint64_t b64 = ((uint64_t)prev << 32) | curr;
        for (uint32_t b = 0; b < 32u; b++) {
            if (((uint32_t)(b64 >> (52u - b)) & 0xFFFu) == 0x801u) {
                *out_word = i;
                *out_bit = b;
                return true;
            }
        }
    }
    return false;
}

// Frame-level oracle: sync-scan the emitted stream, decode at frame stride
// exactly as the firmware does, and judge by header validity plus the
// channel-0 frame counter. Immune to the self-similar-pattern ambiguity
// that defeats bit-level diffing.
typedef struct {
    uint64_t ok;            // frames decoded with valid header + correct content
    uint64_t hdr_fail;      // header verification failures (each = lock loss)
    uint64_t content_bad;   // header ok but samples mismatch the counter frame
    uint64_t skipped;       // frames lost across resyncs
    uint64_t longest_run;   // longest consecutive-ok run (lock viability)
    bool synced;
} FrameVerdict;

static FrameVerdict frame_oracle(void) {
    FrameVerdict v = {0};
    // pack emitted[] bits into words
    static uint32_t words[(uint64_t)N_FRAMES * 8 + 128];
    memset(words, 0, sizeof(words));
    for (uint64_t i = 0; i < n_emitted; i++)
        if (emitted[i]) words[i >> 5] |= 0x80000000u >> (i & 31u);
    rx_words = words;
    rx_nwords = (uint32_t)(n_emitted / 32u);

    uint32_t rd, k;
    if (!rx_scan(&rd, &k, 0)) return v;
    v.synced = true;

    int64_t expect = -1;    // next expected counter value, -1 = unknown
    uint64_t run = 0;
    while (rd + 9 <= rx_nwords) {
        int32_t got[8];
        if (!rx_decode_frame(rd, k, got)) {
            v.hdr_fail++;
            if (run > v.longest_run) v.longest_run = run;
            run = 0;
            uint32_t nrd, nk;
            if (!rx_scan(&nrd, &nk, rd)) break;   // resync like the firmware
            rd = nrd; k = nk;
            expect = -1;
            continue;
        }
        uint32_t ctr = ((uint32_t)got[0] >> 8) & 0xFFFFFFu;   // undo the <<8
        if (ctr < N_FRAMES) {
            bool content = true;
            for (int ch = 1; ch < 8; ch++)
                if (got[ch] != (int32_t)((uint32_t)ref_frames[ctr][ch] << 8)) { content = false; break; }
            if (content) {
                if (expect >= 0 && (int64_t)ctr > expect)
                    v.skipped += (uint64_t)((int64_t)ctr - expect);
                v.ok++;
                run++;
                expect = (int64_t)ctr + 1;
            } else {
                v.content_bad++;
                if (run > v.longest_run) v.longest_run = run;
                run = 0;
            }
        } else {
            v.content_bad++;
            if (run > v.longest_run) v.longest_run = run;
            run = 0;
        }
        rd += 8;
    }
    if (run > v.longest_run) v.longest_run = run;
    return v;
}

// Align emitted to ideal (search ideal's bits [64..128) inside emitted) then
// walk both, classifying divergences by re-alignment with small shifts.
static void diff_streams(void) {
    // find alignment
    uint64_t e0 = 0;
    bool found = false;
    for (uint64_t e = 0; e + 64 < n_emitted && e < 4096; e++) {
        bool m = true;
        for (int i = 0; i < 64; i++)
            if (emitted[e + i] != ideal[64 + i]) { m = false; break; }
        if (m) { e0 = e; found = true; break; }
    }
    if (!found) { printf("  no alignment found at all\n"); return; }

    uint64_t ei = e0, ii = 64;
    uint64_t net_shift_del = 0, net_shift_ins = 0, events = 0, unresolved = 0;
    uint64_t first_event_bit = 0;
    int dumps = 0;
    while (ei + 96 < n_emitted && ii + 96 < n_levels) {
        if (emitted[ei] == ideal[ii]) { ei++; ii++; continue; }
        if (!events) first_event_bit = ii;
        events++;

        if (dumps < 4) {
            printf("  event %llu at ideal bit %llu (frame %llu, bit-in-frame %llu):\n    ideal   ",
                   (unsigned long long)events, (unsigned long long)ii,
                   (unsigned long long)(ii / 256), (unsigned long long)(ii % 256));
            for (int i = -8; i < 24; i++) putchar('0' + ideal[ii + i]);
            printf("\n    emitted ");
            for (int i = -8; i < 24; i++) putchar('0' + emitted[ei + i]);
            printf("\n            --------^\n");
            dumps++;
        }

        // Robust realign: take emitted[ei+8 .. ei+72) and search for it in
        // ideal within [ii-16, ii+48); use the found offset to account the
        // net insertion/deletion.
        bool fixed = false;
        for (int64_t off = -16; off < 48 && !fixed; off++) {
            bool m = true;
            for (int i = 0; i < 64; i++)
                if (emitted[ei + 8 + i] != ideal[(int64_t)ii + off + 8 + i]) { m = false; break; }
            if (m) {
                if (off > 0) net_shift_del += (uint64_t)off;       // emitted lost bits
                else if (off < 0) net_shift_ins += (uint64_t)(-off);
                ii = (uint64_t)((int64_t)ii + off + 8);
                ei += 8;
                fixed = true;
            }
        }
        if (!fixed) { unresolved++; ei += 8; ii += 8; }
        if (events > 5000) break;
    }
    printf("  events=%llu net_deleted=%llu net_inserted=%llu unresolved=%llu (first at ideal bit %llu, frame %llu) emitted=%llu ideal=%llu\n",
           (unsigned long long)events, (unsigned long long)net_shift_del,
           (unsigned long long)net_shift_ins, (unsigned long long)unresolved,
           (unsigned long long)first_event_bit, (unsigned long long)(first_event_bit / 256),
           (unsigned long long)n_emitted, (unsigned long long)(n_levels));
}

static bool run_case(uint32_t fs, double ppm, uint32_t div) {
    uint64_t tx_div = ((uint64_t)SYS_CLK_HZ + fs - 1) / fs;
    double tx_bit_sys = ((double)tx_div / 256.0) / (1.0 + ppm * 1e-6);
    run_pio(tx_bit_sys, div);
    FrameVerdict v = frame_oracle();
    bool clean = v.synced && v.hdr_fail == 0 && v.content_bad == 0 &&
                 v.skipped == 0 && v.ok >= N_FRAMES - 4;
    printf("fs=%u src=%+5.0fppm div=%u (cell %.4f vs bit %.4f): "
           "ok=%llu hdr_fail=%llu bad=%llu skipped=%llu run=%llu %s\n",
           fs, ppm, div, (double)div * 8.0 / 256.0, tx_bit_sys,
           (unsigned long long)v.ok, (unsigned long long)v.hdr_fail,
           (unsigned long long)v.content_bad, (unsigned long long)v.skipped,
           (unsigned long long)v.longest_run, clean ? "CLEAN" : "DIRTY");
    return clean;
}

int main(int argc, char **argv) {
    tx_init();
    gen_stream(12345);
    if (argc == 5) {
        pio_model = atoi(argv[4]);
        run_case((uint32_t)atoi(argv[1]), atof(argv[2]), (uint32_t)atoi(argv[3]));
        return 0;
    }
    int fails = 0;
    printf("==== model 0 (original program, known bad cases must stay bad) ====\n");
    pio_model = 0;
    if (run_case(44100, 0, 871)) fails++;      // must be DIRTY (sim fidelity)
    if (run_case(48000, +100, 799)) fails++;   // must be DIRTY
    printf("==== model 2 (counter-loop, divider 1.0; param = y) ====\n");
    pio_model = 2;
    // y = (C-5)/2: C=27 -> y=11 (44.1k), C=25 -> y=10 (48k)
    const double ppms[] = {-1000, -500, -100, 0, +100, +500, +1000};
    for (int p = 0; p < 7; p++)
        if (!run_case(44100, ppms[p], 11)) fails++;
    for (int p = 0; p < 7; p++)
        if (!run_case(48000, ppms[p], 10)) fails++;
    // Slave acquisition probes exact decoder timings and trusts only a clean
    // header run. It must reject the initial wrong family and accept the
    // matching candidate; DMA rate from a dirty wrong-cell stream is no
    // longer part of the decision.
    printf("==== exact-timing acquisition probes ====\n");
    if (run_case(44100, 0, 10)) fails++;   // initial 48k candidate: reject
    if (!run_case(44100, 0, 11)) fails++;  // alternate 44.1k: accept
    if (run_case(48000, 0, 11)) fails++;   // stale 44.1k candidate: reject
    if (!run_case(48000, 0, 10)) fails++;  // alternate 48k: accept
    printf(fails ? "FAIL: %d\n" : "PASS\n", fails);
    return fails ? 1 : 0;
}
