/*
 * config.h - DSPi minimal build: USB audio in, I2S audio in, FX chain,
 * I2S audio out.
 *
 * This is a from-scratch, minimal replacement for the original DSPi's
 * config.h (which also carried S/PDIF, ADAT, PDM, a persistent-preset
 * system, a vendor USB control protocol, control surfaces/IR remote, and
 * several DSP-island features -- crossfeed, crossover, loudness, psybass,
 * leveller, upmix -- none of which this build includes). Only what the
 * USB/I2S-in -> FX chain -> I2S-out path actually needs.
 */

#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>
#include <stdbool.h>
#include "pico/audio.h"

// ----------------------------------------------------------------------
// Sample rate / block size
// ----------------------------------------------------------------------

// Fixed operating rate. The original device could switch between
// 44100/48000/96000 at the host's request; this build runs a single
// fixed rate to keep the I2S input/output PIO+DMA setup simple (no
// runtime PIO reload / divider recompute).
//
// 96000: this device's I2S input target is a specific PCM1808 breakout
// board that carries its own onboard crystal supplying SCKI directly
// (~24.576MHz per the physical part marking), rather than expecting the
// host to supply MCK. Confirmed against the original DSPi's own console:
// its "Slave" clock mode for this exact ADC shows Master Clock forced
// off and reports "Locked to external clock at 96.0 kHz". Since
// 24,576,000 / 256 = 96,000 exactly, 96kHz is the only sample rate this
// board's fixed-frequency SCKI actually corresponds to -- both this I2S
// input and (since they share one clock domain -- see this file's
// I2S_BCK_PIN comment) I2S output must run at 96kHz for the PCM1808 to
// lock at all, per its datasheet's requirement that BCK/LRCLK stay
// synchronized with SCKI. 44100 and 48000 were both tried at length
// while chasing severe, constant PCM1808 noise that turned out to be
// exactly this rate mismatch -- neither is anywhere near 96000, so the
// ADC could never lock regardless of how precisely either rate's own
// clock divider behaved. 307.2MHz (this board's fixed system clock)
// gives an exact-integer PIO clock divider at 96kHz (50.0), same as at
// 48kHz.
#define SAMPLE_RATE_HZ 96000u

// Samples processed per pipeline call. Matches the original's
// AUDIO_BUFFER_SAMPLES exactly (4ms blocks @ 48kHz) -- every FX effect's
// real-time-safety comments (chunked PSRAM copies, etc.) were reasoned
// about against this same block size.
#define AUDIO_BUFFER_SAMPLES 192u

// ----------------------------------------------------------------------
// Board pins
// ----------------------------------------------------------------------

// USB audio: handled entirely by TinyUSB's device-mode USB PHY (no GPIO
// pins to configure -- the RP2350's USB peripheral is fixed-function).

// I2S: BCK/LRCLK are shared between input and output, but -- unlike an
// earlier revision of this build -- genuinely EXTERNALLY driven by the
// connected PCM1808 breakout board itself, not generated by this device.
// Confirmed directly on real hardware: with this device's own BCK/LRCLK
// pins completely disconnected from the PCM1808, both pins still read
// ~1.6V DC-average on a multimeter (i.e. still actively toggling) --
// this specific board's onboard crystal drives its own BCK/LRCLK
// regardless of what its MD0/MD1 header pins are tied to. Having this
// device ALSO drive those same physical pins (this build's original,
// self-clocking architecture) was direct electrical bus contention
// between two active output drivers, which was the actual root cause of
// a long, otherwise-unexplained PCM1808 noise investigation -- constant
// garbage completely independent of the data line, the analog source,
// or any capture-logic correctness, because the corruption was on
// BCK/LRCLK themselves. See i2s_output.h's top comment for how this
// device's own I2S output now slaves to that external clock instead of
// generating it. Pin numbers otherwise match the original DSPi project's
// own documented PCM1808 wiring guide
// (github.com/WeebLabs/DSPi#hardware-setup) rather than that project's
// generic PICO_I2S_RX_PIN_DEFAULT (GPIO 1) -- the PCM1808-specific guide
// documents GPIO 4 for RX data instead, matching this build's actual
// wiring.
#define I2S_BCK_PIN       14u   // LRCLK = I2S_BCK_PIN + 1 = GPIO 15
#define I2S_DATA_OUT_PIN   6u   // TX (I2S out) serial data
#define I2S_DATA_IN_PIN    4u   // RX (I2S in) serial data -- PCM1808 DOUT

// No MCK (master clock) output from this device: this specific PCM1808
// board's onboard crystal supplies its own SCKI directly (see
// SAMPLE_RATE_HZ's comment above) -- confirmed against the original
// DSPi's own console for this exact ADC, which shows Master Clock
// explicitly forced OFF in its working "Slave" configuration, not merely
// unused. Generating MCK from this device anyway risked electrical
// contention if its output pin happened to be wired to the same
// physical SCKI trace the onboard crystal also drives -- the same class
// of problem BCK/LRCLK had. If a future I2S input device without its
// own crystal needs MCK supplied by this board, see
// pico_audio_i2s_multi's audio_i2s_mck_*() API (already vendored in
// pico-extras, unused by this build) and GPIO 13 (confirmed as this
// chip's clk_gpout0-mapped pin, matching the original project's PCM1808
// wiring guide's own choice for it).

// ----------------------------------------------------------------------
// Firmware version (Query Firmware, fx_control.c)
// ----------------------------------------------------------------------

// Distinct from the original DSPi's version numbering (it was at 1.1.5) --
// this is a different firmware variant (minimal USB/I2S-in -> FX ->
// I2S-out build), not a continuation of that version history.
#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 0
#define FW_VERSION_PATCH 0

// ----------------------------------------------------------------------
// Misc
// ----------------------------------------------------------------------

// Marks a function's code as RAM-resident rather than flash/XIP.
// Required for anything in the per-sample audio hot path so it isn't
// stalled by concurrent flash or (for the FX effects that use it) PSRAM
// QMI-bus traffic -- see fx_delay.c's comment for the detailed
// rationale. Every FX effect file already assumes this macro exists
// under this exact name.
#define DSP_TIME_CRITICAL __attribute__((section(".time_critical")))

#endif // CONFIG_H
